controller_list:
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_hand_controller
    joints:
      - gripper
initial:  # Define initial robot poses.
  - group: arm
    pose: arm_init
  - group: hand
    pose: hand_open